name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Build Assembler
      run: dotnet build 
      working-directory: ./DesignYourOwnCpu/Assembler
    - name: Test Assembler
      run: dotnet test --verbosity normal
      working-directory: ./DesignYourOwnCpu/AssemblerTests
    - name: Build Emulator
      run: dotnet build 
      working-directory: ./DesignYourOwnCpu/Emulator
    - name: Test Emulator
      run: dotnet test --verbosity normal
      working-directory: ./DesignYourOwnCpu/EmulatorTests
